"use strict";
exports.__esModule = true;
var data_1 = require("./data");
var dollar_1 = require("./dollar");
var euro_1 = require("./euro");
var formatoBrasil_1 = require("./formatoBrasil");
var formatoUSA_1 = require("./formatoUSA");
var moeda_1 = require("./moeda");
var real_1 = require("./real");
var formatador;
var moeda = new moeda_1["default"](50.3);
formatador = new real_1["default"](moeda);
console.log(formatador.formatar());
formatador = new dollar_1["default"](moeda);
console.log(formatador.formatar());
formatador = new euro_1["default"](moeda);
console.log(formatador.formatar());
var data = new data_1["default"](new Date());
formatador = new formatoBrasil_1["default"](data);
console.log(formatador.formatar());
formatador = new formatoUSA_1["default"](data);
console.log(formatador.formatar());
